swagger: "2.0"
info:
  version: 1.0.0
  title: Based on "Basic Auth Example"
  description: >
    An example for how to use Auth with Swagger.

host: localhost:3001
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /auth/authenticate:
    post:
      tags:
        - "Authentication"
      summary: "Logs user into the system"
      security:
        - Bearer: []
      parameters:
        - in: "body"
          name: "body"
          description: "User that will log on system"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"
  /auth/register:
    post:
      tags:
        - "Authentication"
      summary: "Create user"
      security:
        - Bearer: []
      parameters:
        - in: "body"
          name: "body"
          description: "User that will be registered on system"
          required: true
          schema:
            $ref: "#/definitions/RegisterUser"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"

  /products:
    get:
      tags:
        - "Products"
      summary: "Finds all products"
      description: "This can only be done by logged user. Returns a list of products"
      security:
        - Bearer: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"
    post:
      tags:
        - "Products"
      summary: "Add a new product to the store"
      description: "This can only be done by super user"
      security:
        - Bearer: []
      parameters:
        - in: "body"
          name: "body"
          description: "Product object that will be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"
  /products/{productId}:
    get:
      tags:
        - "Products"
      summary: "Find product by ID"
      description: "This can only be done by logged user. Returns a single product"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product to return"
          required: true
          type: "number"
      security:
        - Bearer: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"
    put:
      tags:
        - "Products"
      summary: "Update an existing product"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product to be updated"
          required: true
          type: "number"
        - in: "body"
          name: "body"
          description: "Product object that will be updated"
          required: true
          schema:
            $ref: "#/definitions/Product"
      security:
        - Bearer: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"
    delete:
      tags:
        - "Products"
      summary: "Delete product by ID"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product to be deleted"
          required: true
          type: "number"
      security:
        - Bearer: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid request"
        "401":
          description: "You do not have necessary permissions for the resource"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "number"
      title:
        type: "string"
        example: "T Shirt Casual Cotton Short"
      price:
        type: "number"
        example: 12.99
      description:
        type: "string"
        example: "Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees"
      category:
        type: "string"
        enum:
          - "men's clothing"
          - "jewelery"
          - "electronics"
          - "women's clothing"
      image:
        type: "string"
        example: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg"
      rating:
        type: "number"
        example: 3.6
  User:
    type: "object"
    properties:
      userName:
        type: "string"
        example: "admin"
      password:
        type: "string"
        example: "admin"
  RegisterUser:
    type: "object"
    properties:
      userName:
        type: "string"
        example: "user"
      fullName:
        type: "string"
        example: "User"
      email:
        type: "string"
        example: "user@user.com"
      password:
        type: "string"
        example: "user"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
